/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalmedyaapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author samet
 */
public class Frm_KayitOl extends javax.swing.JFrame {

    /**
     * Creates new form Frm_KayitOl
     */
    public Frm_KayitOl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txt_adi = new javax.swing.JTextField();
        txt_soyadi = new javax.swing.JTextField();
        txt_kullaniciadi = new javax.swing.JTextField();
        txtp_sifre = new javax.swing.JPasswordField();
        rdio_kadin = new javax.swing.JRadioButton();
        rdio_erkek = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kaydet = new javax.swing.JButton();
        btn_iptal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAYIT OL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 42, 156, -1));
        getContentPane().add(txt_soyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 77, 156, -1));
        getContentPane().add(txt_kullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 111, 156, -1));
        getContentPane().add(txtp_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 146, 156, -1));

        buttonGroup1.add(rdio_kadin);
        rdio_kadin.setSelected(true);
        rdio_kadin.setText("KADIN");
        getContentPane().add(rdio_kadin, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 186, -1, -1));

        buttonGroup1.add(rdio_erkek);
        rdio_erkek.setText("ERKEK");
        getContentPane().add(rdio_erkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 216, -1, -1));

        jLabel1.setText("Adı");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 45, -1, -1));

        jLabel2.setText("Soyadı");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel3.setText("KullanıcıAdı");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 114, -1, -1));

        jLabel4.setText("Sifre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 149, -1, -1));

        jLabel5.setText("Cinsiyet");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 186, -1, -1));

        btn_kaydet.setText("KAYDET");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 252, 110, 30));

        btn_iptal.setText("İPTAL");
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
        try {
            // TODO add your handling code here:

            USER yenikullanici = new USER();
            yenikullanici.Adi = txt_adi.getText();
            yenikullanici.Soyadi = txt_soyadi.getText();
            yenikullanici.KullaniciAdi = txt_kullaniciadi.getText();
            yenikullanici.Sifre = String.valueOf(txtp_sifre.getPassword());
            yenikullanici.Cinsiyet = rdio_erkek.isSelected();

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/SOSYALMEDYADB", "sa", "as");

            ///kullanıcı adı varmı
            String query = "SELECT KULLANICI_ADI FROM TBL_USER WHERE KULLANICI_ADI='" + yenikullanici.KullaniciAdi + "'";
            Statement stm1 = con.createStatement();

            ResultSet kullanicilar = stm1.executeQuery(query);

            if (kullanicilar.next()) {
                JOptionPane.showMessageDialog(rootPane, yenikullanici.KullaniciAdi + " kullanıcısı  bulunmaktadır");
                return;
            }

            //**********************
            ///max id bul
            query = "SELECT MAX(ID) max_id FROM TBL_USER";
            stm1 = con.createStatement();

            ResultSet idMax = stm1.executeQuery(query);
            int id2 = 0;
            if (idMax.next()) {
                id2 = idMax.getInt("max_id");
            }
            id2++;

            //**********************
            query = "INSERT INTO TBL_USER (ID,KULLANICI_ADI,ADI,SOYADI,SIFRE,CINSIYET) VALUES(?,?,?,?,?,?)";

            PreparedStatement stm = con.prepareStatement(query);

            stm.setInt(1, id2);
            stm.setString(2, yenikullanici.KullaniciAdi);
            stm.setString(3, yenikullanici.Adi);
            stm.setString(4, yenikullanici.Soyadi);
            stm.setString(5, yenikullanici.Sifre);
            stm.setBoolean(6, yenikullanici.Cinsiyet);

            stm.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "KAYIT BAŞARILI");
             Frm_Login log = new Frm_Login();
        log.setVisible(true);
        this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(Frm_KayitOl.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
        // TODO add your handling code here:
        Frm_Login log = new Frm_Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_iptalActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Frm_Login log = new Frm_Login();
        log.setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_KayitOl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iptal;
    private javax.swing.JButton btn_kaydet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rdio_erkek;
    private javax.swing.JRadioButton rdio_kadin;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_kullaniciadi;
    private javax.swing.JTextField txt_soyadi;
    private javax.swing.JPasswordField txtp_sifre;
    // End of variables declaration//GEN-END:variables
}
