/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab12;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

/**
 *
 * @author samet
 */
public class Soru2 extends javax.swing.JFrame {

    /**
     * Creates new form Soru2
     */
    public Soru2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Dosya Yaz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Dosya Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kontrol");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            EntityManagerFactory emf=Persistence.createEntityManagerFactory("BP2_LAB2PU");
            EntityManager em=emf.createEntityManager();
            Query q=em.createQuery("SELECT k FROM Personel k");
            List<Personel>personeller=q.getResultList();
            
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/DEPO", "sa", "as");
            for (Personel personel : personeller) {
                PreparedStatement ps=con.prepareStatement("SELECT * FROM PERSONEL_TELEFON WHERE PERSONEL_ID="+personel.getPerId());
                ResultSet rs=ps.executeQuery();
                int personelTelefonID=0;
                while (rs.next()) {                    
                    personelTelefonID=rs.getInt("TELEFON_ID");
                }
                ps=con.prepareStatement("SELECT * FROM TELEFON WHERE TEL_ID="+personelTelefonID);
                rs=ps.executeQuery();
                while (rs.next()) {                    
                    ObjectOutputStream oOS=new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(personel.getAdi())));
                    oOS.writeUTF(rs.getString("TEL_ADI"));
                    oOS.close();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         EntityManagerFactory emf=Persistence.createEntityManagerFactory("BP2_LAB2PU");
         EntityManager em=emf.createEntityManager();
         Query q=em.createQuery("SELECT k FROM Personel k");
         List<Personel>personeller=q.getResultList();
         int verilenPerId=3;
         String okunanMetin="";
         String okunanKisiAd="";
         for (Personel personel : personeller) {
             if (personel.getPerId()==verilenPerId) {
                 try {
                     ObjectInputStream oOS=new ObjectInputStream(new BufferedInputStream(new FileInputStream(personel.getAdi())));
                     okunanMetin=oOS.readUTF();
                     okunanKisiAd=personel.getAdi();
                     oOS.close();
                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (IOException ex) {
                     Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
        }
        try {
            ObjectOutputStream oOS=new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream("silinenler\\"+okunanKisiAd+".obj")));
            oOS.writeUTF(okunanMetin);
            oOS.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         EntityManagerFactory emf=Persistence.createEntityManagerFactory("BP2_LAB2PU");
         EntityManager em=emf.createEntityManager();
         Query q=em.createQuery("SELECT k FROM Personel k");
         List<Personel>personeller=q.getResultList();
      //   ArrayList<String> paths=new ArrayList();
         for (Personel personel : personeller) {
             try {
                 //   paths.add(personel.getAdi());
                 Path p =Paths.get(personel.getAdi());
                 p.toRealPath();
             } catch (IOException ex) {
                 Logger.getLogger(Soru2.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
//         
//         for (String path : paths) {
//             try {
//                 Path p=Paths.get(path);
//                 p.toRealPath();
//             } catch (IOException ex) {
//                 System.out.println(path+" Müşterisine Ait Bilgi Bulunamadı.");
//             }
//        }
         
         
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
