/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab11;

import bp2_lab8.NewClass;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samet
 */
public class Soru3 extends javax.swing.JFrame {

    /**
     * Creates new form Soru3
     */
    DefaultTableModel dtm;

    public Soru3() {
        initComponents();

        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"ID", "ADI", "SOYADI", "MAAS"});
        jTable1.setModel(dtm);
        try {
            // bağlantı için
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/PERSONELDB", "sa", "as");
            // iletişimi acıyor
            Statement stmt = con.createStatement();
            // veritabanında sorgu çalıştırıp bize geri tablo döndürüyor.
            ResultSet rs = stmt.executeQuery("SELECT * FROM PERSONEL");

            while (rs.next()) {
                int id = rs.getInt("ID");
                String adi = rs.getString("ADI");
                String soyadi = rs.getString("SOYADI");
                int maas = rs.getInt("MAAS");
                dtm.addRow(new Object[]{id, adi, soyadi, maas});
            }

        } catch (SQLException ex) {
            Logger.getLogger(NewClass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_yaz = new javax.swing.JButton();
        btn_oku = new javax.swing.JButton();
        txt_adi = new javax.swing.JTextField();
        txt_soyadi = new javax.swing.JTextField();
        btn_toplamtutaryaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 485, 222));

        btn_yaz.setText("Yaz");
        btn_yaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yazActionPerformed(evt);
            }
        });
        getContentPane().add(btn_yaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        btn_oku.setText("Oku");
        btn_oku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_oku, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));
        getContentPane().add(txt_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 100, -1));
        getContentPane().add(txt_soyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 90, -1));

        btn_toplamtutaryaz.setText("toplam");
        btn_toplamtutaryaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamtutaryazActionPerformed(evt);
            }
        });
        getContentPane().add(btn_toplamtutaryaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_yazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yazActionPerformed
        // TODO add your handling code here:

        try {
            // bağlantı için
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/PERSONELDB", "sa", "as");
            // iletişimi acıyor
            Statement stmt = con.createStatement();
            // veritabanında sorgu çalıştırıp bize geri tablo döndürüyor.
            ResultSet rs = stmt.executeQuery("SELECT * FROM PERSONEL");
            while (rs.next()) {
                int id = rs.getInt("ID");
                String adi = rs.getString("ADI");
                String soyadi = rs.getString("SOYADI");
                int maas = rs.getInt("MAAS");

                BufferedWriter output = new BufferedWriter(new FileWriter(id + "_" + adi + "_" + soyadi + ".txt"));
                output.write(id + " " + adi + " " + soyadi + " " + maas + "\n");
                output.close();
            }

        } catch (SQLException ex) {
            Logger.getLogger(NewClass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Soru3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_yazActionPerformed

    private void btn_okuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okuActionPerformed

        try {
            // TODO add your handling code here:

            int rowindex = jTable1.getSelectedRow();
            if (rowindex < 0) {
                return;
            }
            String id = jTable1.getValueAt(rowindex, 0).toString();
            String adi = jTable1.getValueAt(rowindex, 1).toString();
            String soyadi = jTable1.getValueAt(rowindex, 2).toString();

            BufferedReader input = new BufferedReader(new FileReader(id + "_" + adi + "_" + soyadi + ".txt"));
            String[] values = input.readLine().split(" ");
            txt_adi.setText(values[1]);
            txt_soyadi.setText(values[2]);

            input.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Soru3.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Soru3.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_okuActionPerformed

    private void btn_toplamtutaryazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamtutaryazActionPerformed
        // TODO add your handling code here:
        try {
            // bağlantı için
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/PERSONELDB", "sa", "as");
            // iletişimi acıyor
            Statement stmt = con.createStatement();
            // veritabanında sorgu çalıştırıp bize geri tablo döndürüyor.
            ResultSet rs = stmt.executeQuery("SELECT * FROM PERSONEL");
            int toplam = 0;
            while (rs.next()) {
                int id = rs.getInt("ID");
                String adi = rs.getString("ADI");
                String soyadi = rs.getString("SOYADI");
                int maas = rs.getInt("MAAS");
                toplam += maas;

            }
            PrintWriter printw = new PrintWriter(new FileWriter("toplam.txt"));
            printw.println("Ahmet AK isimli müşterinin toplam satışı " + toplam + " TL");

            printw.close();
        } catch (SQLException ex) {
            Logger.getLogger(NewClass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Soru3.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_toplamtutaryazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_oku;
    private javax.swing.JButton btn_toplamtutaryaz;
    private javax.swing.JButton btn_yaz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_soyadi;
    // End of variables declaration//GEN-END:variables
}
