/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab6;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author samet
 */
public class SayiTahmin extends javax.swing.JFrame {

    int sayi;
    int tahminsayisi;

    /**
     * Creates new form SayiTahmin
     */
    public SayiTahmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_yenioyun = new javax.swing.JButton();
        btn_tahmin = new javax.swing.JButton();
        txt_tahmin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_yenioyun.setText("Yeni Oyun");
        btn_yenioyun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yenioyunActionPerformed(evt);
            }
        });

        btn_tahmin.setText("Tahmin Et");
        btn_tahmin.setEnabled(false);
        btn_tahmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tahminActionPerformed(evt);
            }
        });

        txt_tahmin.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_yenioyun)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_tahmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_tahmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_yenioyun)
                .addGap(22, 22, 22)
                .addComponent(txt_tahmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_tahmin)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tahminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tahminActionPerformed
        // TODO add your handling code here:
        tahminsayisi++;
        int tahminsayi = Integer.parseInt(txt_tahmin.getText());
        if (tahminsayi == sayi) {
            JOptionPane.showMessageDialog(rootPane, tahminsayisi + ". TAHMİNDE BİLDİNİZ :)");

            tahminsayi = 0;

            txt_tahmin.setEnabled(false);
            btn_tahmin.setEnabled(false);
        } else if (tahminsayi < sayi) {
            JOptionPane.showMessageDialog(rootPane, tahminsayisi + ". TAHMİN.  BİLEMEDİNİZ. DAHA BÜYÜK SAYI GİRİZ :(");
        } else {
            JOptionPane.showMessageDialog(rootPane, tahminsayisi + ". TAHMİN.BİLEMEDİNİZ. DAHA KÜCÜK SAYI GİRİZ :(");
        }

        txt_tahmin.setText("");


    }//GEN-LAST:event_btn_tahminActionPerformed

    private void btn_yenioyunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yenioyunActionPerformed
        // TODO add your handling code here:
        Random rnd = new Random();
        
        sayi = rnd.nextInt(100);
        tahminsayisi = 0;
        txt_tahmin.setEnabled(true);
        btn_tahmin.setEnabled(true);

    }//GEN-LAST:event_btn_yenioyunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SayiTahmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SayiTahmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SayiTahmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SayiTahmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SayiTahmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tahmin;
    private javax.swing.JButton btn_yenioyun;
    private javax.swing.JTextField txt_tahmin;
    // End of variables declaration//GEN-END:variables
}
