/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab2;

import javax.swing.DefaultListModel;

/**
 *
 * @author samet
 */
public class Soru_5 extends javax.swing.JFrame {

    /**
     * Creates new form Soru_5
     */
    
     DefaultListModel dm1=new DefaultListModel();
     DefaultListModel dm2=new DefaultListModel();
    public Soru_5() {
        initComponents();
        
          lstb_liste1.setModel(dm1);
          lstb_liste2.setModel(dm2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_isim = new javax.swing.JTextField();
        btn_ekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstb_liste1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstb_liste2 = new javax.swing.JList<>();
        btn_add = new javax.swing.JButton();
        btn_addall = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_isim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, -1));

        btn_ekle.setText("EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 13, -1, -1));

        jScrollPane1.setViewportView(lstb_liste1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 86, 60, -1));

        jScrollPane2.setViewportView(lstb_liste2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, -1));

        btn_add.setText(">");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 86, -1, -1));

        btn_addall.setText(">>");
        btn_addall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addallActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addall, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 118, -1, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 150, -1, -1));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 182, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        // TODO add your handling code here:
        dm1.addElement(txt_isim.getText());
      
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        dm2.addElement(lstb_liste1.getSelectedValue());
        dm1.removeElement(lstb_liste1.getSelectedValue());
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_addallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addallActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dm1.size(); i++) {
             dm2.addElement(dm1.getElementAt(i));
          
        }
           dm1.removeAllElements();
    }//GEN-LAST:event_btn_addallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addall;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstb_liste1;
    private javax.swing.JList<String> lstb_liste2;
    private javax.swing.JTextField txt_isim;
    // End of variables declaration//GEN-END:variables
}
