/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Work_1;

import java.awt.Color;
import java.awt.Point;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;

/**
 *
 * @author samet
 */
public class Soru_1 extends javax.swing.JFrame {

    /**
     * Creates new form Soru_1
     */
    public Soru_1() {
        initComponents();
       jComboBox1.addItem("şili");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_click = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_kac = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_click.setText("Click");
        btn_click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clickActionPerformed(evt);
            }
        });
        getContentPane().add(btn_click, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 13, -1, -1));

        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        getContentPane().add(btn_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 68, -1, -1));

        jCheckBox1.setText("Visible");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 13, -1, -1));

        btn_kac.setText("Kac");
        btn_kac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_kacFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_kacFocusLost(evt);
            }
        });
        btn_kac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kacMouseExited(evt);
            }
        });
        getContentPane().add(btn_kac, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 122, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul", "Ankara", "Bayburt", "Sivas", "Giresun" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, 40));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "fdsfsd" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 170, 110));

        jButton1.setText("Aktar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clickActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btn_clickActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        Soru_1 newsoru1=new Soru_1();
        newsoru1.setDefaultCloseOperation(3);
        newsoru1.setVisible(true);
    }//GEN-LAST:event_btn_newActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            btn_click.setVisible(false);
        }
        else
        {
            btn_click.setVisible(true);
        }
        
    
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void btn_kacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kacMouseEntered
        // TODO add your handling code here:
        
        //btn_kac.setLocation(new Point(btn_kac.getLocation().x+5,btn_kac.getLocation().y+5 ));
        btn_kac.setVisible(false);
    }//GEN-LAST:event_btn_kacMouseEntered

    private void btn_kacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kacMouseExited
        // TODO add your handling code here:
        
        btn_kac.setVisible(true);
    }//GEN-LAST:event_btn_kacMouseExited

    private void btn_kacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_kacFocusGained
        // TODO add your handling code here:
        btn_kac.setBackground(Color.red);
    }//GEN-LAST:event_btn_kacFocusGained

    private void btn_kacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_kacFocusLost
        // TODO add your handling code here:
         btn_kac.setBackground(Color.green);
    }//GEN-LAST:event_btn_kacFocusLost
    DefaultListModel lm=new DefaultListModel();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < jComboBox1.getItemCount(); i++) {
           lm.addElement(jComboBox1.getItemAt(i));
        }
        jList1.setModel(lm);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText(jComboBox1.getSelectedItem().toString());
        
        String satir = "[0]|1|[2]|4|3";
        StringTokenizer st = new StringTokenizer(satir, "|");
        
        while (st.hasMoreElements()) {
            String mytoken1 = st.nextElement().toString();
            if(!(mytoken1.contains("[") || mytoken1.contains("]")))
            {
                 System.out.println(mytoken1);
            }
           
            
//            StringTokenizer st2 = new StringTokenizer(mytoken1, " ");
//            while (st2.hasMoreElements()) {
//                String mytoken2 = st2.nextElement().toString();
//               // System.out.println(mytoken2);
//                mytoken2 = mytoken2.replace("[", "").replace("]", "");
//                System.out.println(mytoken2);
//            }
        }

		

        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru_1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_click;
    private javax.swing.JButton btn_kac;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
