/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab3;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samet
 */
public class HastaApp extends javax.swing.JFrame {

    /**
     * Creates new form HastaApp
     */
    DefaultTableModel dtm;

    public HastaApp() {
        initComponents();
        String[] ColoumNames = {"ID", "ADI", "SOYAD", "DOKTOR"};
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(ColoumNames);
        tbl_liste.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_hastaId = new javax.swing.JTextField();
        txt_hastaName = new javax.swing.JTextField();
        txt_hastaSoyad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_ekle = new javax.swing.JButton();
        btn_degistir = new javax.swing.JButton();
        btn_sorgula = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_liste = new javax.swing.JTable();
        cmbx_hastaDoktor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_hastaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 220, -1));
        getContentPane().add(txt_hastaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));
        getContentPane().add(txt_hastaSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 100, -1));

        jLabel1.setText("DOKTOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel3.setText("AD SOYAD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btn_ekle.setText("EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 90, 50));

        btn_degistir.setText("DEĞİŞTİR");
        btn_degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_degistirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_degistir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 90, 50));

        btn_sorgula.setText("SORGULA");
        btn_sorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sorgulaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sorgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, 50));

        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 90, 50));

        tbl_liste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listeMouseClicked(evt);
            }
        });
        tbl_liste.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tbl_listeInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_liste);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 520, 170));

        cmbx_hastaDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Selim BAKAR", "Dr. Ferhat Pekmez", "Dr. Helin Gitmez" }));
        getContentPane().add(cmbx_hastaDoktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        // TODO add your handling code here:
        Hasta yenihasta = new Hasta();
        yenihasta.Id = txt_hastaId.getText();
        yenihasta.Adi = txt_hastaName.getText();
        yenihasta.Soyadi = txt_hastaSoyad.getText();
        yenihasta.Doktor = cmbx_hastaDoktor.getSelectedItem().toString();

        Hasta.Hastalar.add(yenihasta);

        dtm.setRowCount(0);
        for (Hasta hasta : Hasta.Hastalar) {
            dtm.addRow(new Object[]{hasta.Id, hasta.Adi, hasta.Soyadi, hasta.Doktor});
        }
        Listele();
        Reset();

    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        // TODO add your handling code here:
        if (tbl_liste.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bir Hasta Seçmelisiniz");
            return;
        }
        Hasta.Hastalar.remove(tbl_liste.getSelectedRow());

        Listele();
        Reset();


    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_sorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sorgulaActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        for (Hasta hasta : Hasta.Hastalar) {
            if (hasta.Id.startsWith(txt_hastaId.getText())) {
                dtm.addRow(new Object[]{hasta.Id, hasta.Adi, hasta.Soyadi, hasta.Doktor});
            }

        }


    }//GEN-LAST:event_btn_sorgulaActionPerformed
     Hasta degisecekHasta;
    private void btn_degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_degistirActionPerformed
        // TODO add your handling code here:
         if (tbl_liste.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bir Hasta Seçmelisiniz");
            return;
        }
        degisecekHasta.Id = txt_hastaId.getText();
        degisecekHasta.Adi = txt_hastaName.getText();
        degisecekHasta.Soyadi = txt_hastaSoyad.getText();
        degisecekHasta.Doktor = cmbx_hastaDoktor.getSelectedItem().toString();
        Listele();
 
        
    }//GEN-LAST:event_btn_degistirActionPerformed

    private void tbl_listeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbl_listeInputMethodTextChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tbl_listeInputMethodTextChanged

    private void tbl_listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listeMouseClicked
        // TODO add your handling code here:
           if (tbl_liste.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bir Hasta Seçmelisiniz");
            return;
        }
        degisecekHasta= Hasta.Hastalar.get(tbl_liste.getSelectedRow());
        txt_hastaId.setText(degisecekHasta.Id);
        txt_hastaName.setText(degisecekHasta.Adi);
        txt_hastaSoyad.setText(degisecekHasta.Soyadi);
        cmbx_hastaDoktor.setSelectedItem(degisecekHasta.Doktor); 
    }//GEN-LAST:event_tbl_listeMouseClicked

    private void Reset() {
        txt_hastaId.setText("");
        txt_hastaName.setText("");
        txt_hastaSoyad.setText("");
        cmbx_hastaDoktor.setSelectedIndex(0);
    }

    private void Listele() {
        dtm.setRowCount(0);
        for (Hasta hasta : Hasta.Hastalar) {
            dtm.addRow(new Object[]{hasta.Id, hasta.Adi, hasta.Soyadi, hasta.Doktor});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_degistir;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_sorgula;
    private javax.swing.JComboBox<String> cmbx_hastaDoktor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_liste;
    private javax.swing.JTextField txt_hastaId;
    private javax.swing.JTextField txt_hastaName;
    private javax.swing.JTextField txt_hastaSoyad;
    // End of variables declaration//GEN-END:variables
}
