/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab8;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author samet
 */
public class Soru1 extends javax.swing.JFrame {

    /**
     * Creates new form Soru1
     */
    public Soru1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_adi = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_soyadi = new javax.swing.JTextField();
        txt_maas = new javax.swing.JTextField();
        btn_sorgula = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_yeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 40, -1));
        getContentPane().add(txt_soyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, -1));
        getContentPane().add(txt_maas, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 172, 110, -1));

        btn_sorgula.setText("SORGULA");
        btn_sorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sorgulaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sorgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel1.setText("MAAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setText("ADI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setText("SOYADI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        btn_yeni.setText("YENİ");
        btn_yeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yeniActionPerformed(evt);
            }
        });
        getContentPane().add(btn_yeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sorgulaActionPerformed
        // TODO add your handling code here:
        txt_adi.setText("");
        txt_soyadi.setText("");
        txt_maas.setText("");

        if (txt_id.getText() == null || txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ID değerini girmelisiniz");
            return;
        }
        int gelenid = Integer.parseInt(txt_id.getText());
        try {
            // bağlantı için
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/PERSONELDB", "sa", "as");
            // iletişimi acıyor
            Statement stmt = con.createStatement();
            // veritabanında sorgu çalıştırıp bize geri tablo döndürüyor.
            ResultSet rs = stmt.executeQuery("SELECT * FROM PERSONEL WHERE ID=" + gelenid);

            while (rs.next()) {
                int id = rs.getInt("ID");

                String adi = rs.getString("ADI");
                txt_adi.setText(adi);
                String soyadi = rs.getString("SOYADI");
                txt_soyadi.setText(soyadi);
                int maas = rs.getInt("MAAS");
                txt_maas.setText(maas + "");

            }
        } catch (SQLException ex) {
            Logger.getLogger(NewClass.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_sorgulaActionPerformed

    private void btn_yeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yeniActionPerformed
        // TODO add your handling code here:

        try {
            // bağlantı için
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/PERSONELDB", "sa", "as");
            // iletişimi acıyor
            Statement stmt = con.createStatement();
            // veritabanında sorgu çalıştırıp bize geri tablo döndürüyor.
            ResultSet rs = stmt.executeQuery("SELECT * FROM PERSONEL");
            int enbuyuk = -1;
            while (rs.next()) {
                int id = rs.getInt("ID");
                if (enbuyuk < id) {
                    enbuyuk = id;
                    String adi = rs.getString("ADI");
                    txt_adi.setText(adi);
                    String soyadi = rs.getString("SOYADI");
                    txt_soyadi.setText(soyadi);
                    int maas = rs.getInt("MAAS");
                    txt_maas.setText(maas + "");

                }

            }
            JOptionPane.showMessageDialog(rootPane, "en büyük id="+ enbuyuk);

        } catch (SQLException ex) {
            Logger.getLogger(NewClass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_yeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sorgula;
    private javax.swing.JButton btn_yeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_maas;
    private javax.swing.JTextField txt_soyadi;
    // End of variables declaration//GEN-END:variables
}
