/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab7;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author samet
 */
public class Soru_3 extends javax.swing.JFrame {

    /**
     * Creates new form Soru_3
     */
    public Soru_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_fatura = new javax.swing.JTextField();
        btn_ekle = new javax.swing.JButton();
        cmb_fatura = new javax.swing.JComboBox<>();
        cmb_hatalifatura = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_fatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 40, 90, -1));

        btn_ekle.setText("Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        getContentPane().add(cmb_fatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, -1));

        getContentPane().add(cmb_hatalifatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        // TODO add your handling code here:

        Fatura f = new Fatura();

        try {
            int sayi = Integer.parseInt(txt_fatura.getText());
            f.setFiyat(sayi);
            cmb_fatura.addItem(txt_fatura.getText());
        } catch (SifirdanKucukException ex) {
            cmb_hatalifatura.addItem(txt_fatura.getText());
        } 
catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Hatalı Format");
            txt_fatura.setText("");
        }
//        catch(Exception ex)
//        {
//            System.out.println("Hata: "+ex.getClass()+" Mesaj:"+ex.getMessage()+ ex.getStackTrace()[0]);
//        }

    }//GEN-LAST:event_btn_ekleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JComboBox<String> cmb_fatura;
    private javax.swing.JComboBox<String> cmb_hatalifatura;
    private javax.swing.JTextField txt_fatura;
    // End of variables declaration//GEN-END:variables
}
